#FROM registry.access.redhat.com/ubi8/ubi
FROM registry.access.redhat.com/ubi8/ubi:8.3


# Install Apache & PHP
RUN yum --enablerepo=ubi-8-codeready-builder -y update \
  && yum --disableplugin=subscription-manager -y module enable php:7.4 \
  && yum --disableplugin=subscription-manager -y install httpd php php-bcmath php-cli php-common php-gd php-intl php-ldap php-mbstring \
    php-mysqlnd php-pear php-soap php-xml php-xmlrpc php-zip php-pdo php-xml php-pear php-devel gcc-c++ gcc make \
  && yum --disableplugin=subscription-manager clean all
# TODO, caching of php ?

# Install RE2C package
# Make sure re2c is required
# Or it can compile from source
# RUN rpm -Uvh http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/re2c-0.14.3-2.el8.x86_64.rpm
#RUN dnf config-manager --add-repo http://mirror.centos.org/centos/8/PowerTools/x86_64/os/ \
#  && http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official \
#  && dnf -y install re2c

# Compatibility for UBI8
RUN yum config-manager --add-repo http://mirror.centos.org/centos/8/BaseOS/x86_64/os/ \
  && echo "gpgkey=http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official" >> /etc/yum.repos.d/mirror.centos.org_centos_8_BaseOS_x86_64_os_.repo \
  && yum --disableplugin=subscription-manager -y install e2fsprogs

# Install mssql driver
RUN curl https://packages.microsoft.com/config/rhel/8/prod.repo > /etc/yum.repos.d/mssql-release.repo
#RUN yum remove unixODBC-utf16 unixODBC-utf16-devel 
ENV ACCEPT_EULA=Y
ENV PATH=${PATH}:/opt/mssql/bin:/opt/mssql-tools/bin
# export ACCEPT_EULA=Y
# export PATH=${PATH}:/opt/mssql/bin:/opt/mssql-tools/bin
RUN yum --disableplugin=subscription-manager -y install msodbcsql17 mssql-tools unixODBC-devel
#RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile \
#    && echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc \
#    && source ~/.bashrc


# Install PHP MSSQL PDO
RUN pecl install sqlsrv \
  && pecl install pdo_sqlsrv \
  && chmod 755 /usr/lib64/php/modules/sqlsrv.so \
  && chmod 755 /usr/lib64/php/modules/pdo_sqlsrv.so \
  && echo extension=pdo_sqlsrv.so >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/30-pdo_sqlsrv.ini \
  && echo extension=sqlsrv.so >> `php --ini | grep "Scan for additional .ini files" | sed -e "s|.*:\s*||"`/20-sqlsrv.ini 
#  && setsebool -P httpd_can_network_connect_db 1

# Update Apache Configuration
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
# export APACHE_DOCUMENT_ROOT=/var/www/html/public
RUN sed -E -i -e '/<Directory "\/var\/www\/html">/,/<\/Directory>/s/AllowOverride None/AllowOverride All/' /etc/httpd/conf/httpd.conf \
  && sed -E -i -e 's/DirectoryIndex (.*)$/DirectoryIndex index.php \1/g' /etc/httpd/conf/httpd.conf \
  && sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/httpd/conf/httpd.conf \
  && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/httpd/conf/httpd.conf

# enable url rewrite
# RUN sed -i -r "s,^#(LoadModule. rewrite_module modules/mod_rewrite.so),\1/g" /etc/httpd/conf/httpd.conf

# Permission Update and Enable reading environment variable
# Putting EGPCS in php.ini if $_ENV is necessary
RUN sed -i 's/listen.acl_users = apache,nginx/listen.acl_users =/' /etc/php-fpm.d/www.conf \
  && mkdir /run/php-fpm \
  && chgrp -R 0 /var/log/httpd /var/run/httpd /run/php-fpm \
  && chmod -R g=u /var/log/httpd /var/run/httpd /run/php-fpm \
  && sed -i 's/;clear_env = no/clear_env = no/' /etc/php-fpm.d/www.conf


# For testing purpose
RUN yum --disableplugin=subscription-manager -y install iputils bind-utils nmap-ncat
ADD index.php /var/www/html/public/index.php
ADD info.php /var/www/html/public/info.php
ADD sqlconnect.php /var/www/html/public/sqlconnect.php
ADD sqlconnect2.php /var/www/html/public/sqlconnect2.php
RUN sed -i 's/Listen 80/Listen 8080/' /etc/httpd/conf/httpd.conf 
# EXPOSE 8080


EXPOSE 80


# Start Apache
USER 1001
CMD php-fpm & httpd -D FOREGROUND
#CMD ["/usr/sbin/httpd","-D","FOREGROUND"]